// Test definitions. Do NOT edit this file!
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "main.hpp"

// ─────────────────────────────────────────────────────────────────────────────
// [T1]  basic match — substring exists, returns its starting index
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T1a: 'col' in 'Chocolate' at index 3", "[T1]")
{
    char cstr[] = "Chocolate";
    char user[] = "col";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == 3);
}

TEST_CASE("T1b: 'ram' in 'C++ Programming' at index 8", "[T1]")
{
    char cstr[] = "C++ Programming";
    char user[] = "ram";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == 8);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T2]  not found — returns -1
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T2a: 'xyz' not in 'Chocolate' returns -1", "[T2]")
{
    char cstr[] = "Chocolate";
    char user[] = "xyz";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == -1);
}

TEST_CASE("T2b: case-sensitive: 'COL' not in 'Chocolate' returns -1", "[T2]")
{
    char cstr[] = "Chocolate";
    char user[] = "COL";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == -1);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T3]  match at beginning / at end / single character
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T3a: match at beginning — 'Choc' in 'Chocolate' at index 0", "[T3]")
{
    char cstr[] = "Chocolate";
    char user[] = "Choc";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == 0);
}

TEST_CASE("T3b: match at end — 'late' in 'Chocolate' at index 5", "[T3]")
{
    char cstr[] = "Chocolate";
    char user[] = "late";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == 5);
}

// ─────────────────────────────────────────────────────────────────────────────
// [T4]  edge cases — userstr longer than cstr / first occurrence on duplicates
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE("T4a: userstr longer than cstr returns -1", "[T4]")
{
    char cstr[] = "abc";
    char user[] = "abcde";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == -1);
}

TEST_CASE("T4b: 'ab' in 'cababab' returns first occurrence (index 1)", "[T4]")
{
    char cstr[] = "cababab";
    char user[] = "ab";
    int pos = finduserstring(cstr, strlen(cstr), user, strlen(user));
    REQUIRE(pos == 1);
}
